[package]
name = "chip8"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
env_logger = "0.10"
log = { version = "0.4", features = ["release_max_level_off"] }
sdl2 = "0.35"
